name: quasiflow2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Nextflow
  - nextflow=24.10.3

  # Python core
  - python=3.12.8

  # QuasiFlow tools
  - quasitools=0.7.0

  # Quality control and trimming tools
  - fastqc=0.12.1
  - multiqc=1.25.2
  - trim-galore=0.6.10

